### ISSUE TITLE
install.exe(0.2.3) crash with flashing text

### ISSUE THREAD

**Issue by L0891-3BDBFF** [prodzpod/ZeroDayToolKit#3]
when I trying to use install.exe(0.2.3) to install 0DTK it crash with some flashing text(pretty hard to capture):

---
Traceback (most recent call last):
  File "install.py", line 268, in <module>
    root = Tk()
  File "tkinter\__init__.py", line 2261, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {C:\Users\[My username]\AppData\Local\Temp\_MEI506242\tcl} C:/Users/[My username]/AppData/Local/Temp/_MEI506242/tcl8.6 C:/Users/[My username]/AppData/Local/Temp/lib/tcl8.6 {E:/[my browser download directory]/lib/tcl8.6} E:/lib/tcl8.6 {E:/[my browser download directory]/library} E:/library E:/tcl8.6.9/library E:/tcl8.6.9/library

This probably means that Tcl wasn't installed properly.

[49104] Failed to execute script install
---

but when I run install.py in command line it works all fine

**Comment by prodzpod** [comment]
works on my machine

**Comment by prodzpod** [comment]
is it still bad
